version: 2.1



workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master

jobs:
  build:
    executor: image-builder
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:latest .devcontainer
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish:
    executor: image-builder
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Archived Docker Image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo $DOCKERHUB_PASS |
              docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $IMAGE_NAME:latest

executors:
  image-builder:
    environment:
      IMAGE_NAME: thebearingedge/code-container
    docker:
      - image: circleci/buildpack-deps:stretch
